max_width = 120
tab_spaces = 4
fn_single_line = true
match_block_trailing_comma = true
imports_granularity="Crate"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
normalize_doc_attributes = true
edition = "2018"
